# Generated by Django 3.0 on 2019-12-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='github_login',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ldap_login',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
